### PR TITLE
Update to 102.0.5005.115-1

### PR DESCRIPTION
**Pull request by teeminus**
No patches needed to be updated. Compiled and tested successfully.

### CODE REVIEW

**Review by PF4Public — APPROVED** [review]

**Review by networkException — APPROVED** [review]

**Comment by networkException** [comment]
Do you want to push a new tag as well?

**Comment by teeminus** [comment]
I just did that while you were writing 😂

**Comment by teeminus** [comment]
Can we automate the tag creation via GH Actions like in the bare repo?

**Comment by networkException** [comment]
bare repo?

**Comment by teeminus** [comment]
*base repo 😅

**Comment by networkException** [comment]
The base repo doesn't have any git tag automation, tags get created manually (usually by me)

It does have automation for creating github releases. The tag that you just pushed is the first to run the actions workflow introduced in #125, meaning that a release with compiled binaries will release in ~18-25 hours

**Comment by teeminus** [comment]
So in the base repo, pushing a new tag triggers the creation of a release. That explains why the tag was present before I got the release notification.

**Pull request merged**
