### PR TITLE
Update to 104.0.5112.81

### PR DESCRIPTION
**Pull request by teeminus**
THIS PR REQUIRES https://github.com/ungoogled-software/ungoogled-chromium/pull/2029 TO BE MERGED PRIOR.

image

They added a new clang-15 feature with this update which was easy to patch luckily. Instead of creating a new patch I renamed `windows-fix-unknown-no-opaque-pointers-clang-parameter.patch` to `windows-fix-unknown-clang-parameters.patch` and added the required modifications there.

Besides that I fixed a minor typo in the readme.

Once https://github.com/ungoogled-software/ungoogled-chromium/pull/2029 is merged I will update the submodule and remove the draft state from this PR.

### CODE REVIEW

**Comment by tangalbert919** [comment]
Chromium 104.0.5112.81 has been pushed to the stable branch, so now would be a good time to update this PR.

In addition, a release candidate for Clang 15 has been released. Whether or not you choose to use this version is up to you.

**Comment by teeminus** [comment]
Thanks for the hint. I started updating the patches a few hours ago and I am currently waiting for it to compile. After than I will update this PR.

Currently it looks like that I only have to change the caption of the PR, btw.

**Review by Nifury — DISMISSED** [review]
Builds and runs. 
image

**Comment by teeminus** [comment]
I updated the submodule. Unfortunatelly Github does not allow changing the source branch of a PR, otherwise I would have changed it to a renamed branch which matches the version number.

**Review by Nifury — APPROVED** [review]

**Pull request merged**
