### PR TITLE
Update to Chromium 98.0.4758.80

### PR DESCRIPTION
**Pull request by teeminus**
Reworking the windows-fix-building-without-safebrowsing.patch was quite challenging as there were a lot of changes in the affected files.

Nevertheless, compiling of the lastest ungoogled-chromium for windows now works:
image

### CODE REVIEW

**Comment by playgithub** [comment]
https://github.com/TomDotBat/ungoogled-chromium-windows merges https://github.com/teeminus/ungoogled-chromium-windows for v98.0.4758.80
After 3 tests, it is **always** interrupted by `Ctrl+C` automatically after compiling many files (like 2000 more files).
After the interrupt, if try to continue by running `ninja` manually, it'll succeed finally.
What's the problem? BTW not sure which repo causes the problem.

**Comment by playgithub** [comment]
> periodically interrupts the compiler to work around the GitHub action runner time limit

Does the interrupted  show as  a keyboard interruption by `Ctrl+C`?

**Comment by TomDotBat** [comment]
> Does the it show as a keyboard interruption by `Ctrl+C`?
Should do.

**Comment by teeminus** [comment]
There is a new PR to Chrome 99.

**Pull request closed without merging**
