### PR TITLE
Update to Chromium 84.0.4147.89

### PR DESCRIPTION
**Pull request by tangalbert919**
This PR is currently incomplete, as I have not managed to successfully build yet. More commits will be on the way.

Notable changes:
* A snapshot of LLVM 11.0.0 is in use.
* Ninja has been updated to 1.10.0.
* The `full_wpo_on_official` GN flag has been removed, as it is no longer used.

Current issues:
* `/showIncludes` needs to be removed from `build/toolchain/win/BUILD.gn`.
* Whatever it is that is happening here:
```
C:/Python27/python.exe ../../third_party/blink/renderer/bindings/scripts/generate_bindings.py enumeration --web_idl_database gen/third_party/blink/renderer/bindings/web_idl_database.pickle --root_src_dir ../../ --root_gen_dir gen --output_core_reldir third_party/blink/renderer/bindings/core/v8/ --output_modules_reldir third_party/blink/renderer/bindings/modules/v8/
Traceback (most recent call last):
  File "../../third_party/blink/renderer/bindings/scripts/generate_bindings.py", line 86, in <module>
    main()
  File "../../third_party/blink/renderer/bindings/scripts/generate_bindings.py", line 82, in main
    dispatch_table[task](web_idl_database=web_idl_database)
  File "E:\ungoogled-chromium-windows\build\src\third_party\blink\renderer\bindings\scripts\bind_gen\enumeration.py", line 360, in generate_enumerations
    generate_enumeration(enumeration)
  File "E:\ungoogled-chromium-windows\build\src\third_party\blink\renderer\bindings\scripts\bind_gen\enumeration.py", line 354, in generate_enumeration
    write_code_node_to_file(header_node, path_manager.gen_path_to(header_path))
  File "E:\ungoogled-chromium-windows\build\src\third_party\blink\renderer\bindings\scripts\bind_gen\codegen_utils.py", line 153, in write_code_node_to_file
    format_result = style_format.auto_format(rendered_text, filename=filepath)
  File "E:\ungoogled-chromium-windows\build\src\third_party\blink\renderer\bindings\scripts\bind_gen\style_format.py", line 53, in auto_format
    return clang_format(contents, filename)
  File "E:\ungoogled-chromium-windows\build\src\third_party\blink\renderer\bindings\scripts\bind_gen\style_format.py", line 61, in clang_format
    return _invoke_format_command(command_line, filename, contents)
  File "E:\ungoogled-chromium-windows\build\src\third_party\blink\renderer\bindings\scripts\bind_gen\style_format.py", line 74, in _invoke_format_command
    command_line, stdin=subprocess.PIPE, stdout=subprocess.PIPE)
  File "C:\Python27\lib\subprocess.py", line 394, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 644, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified
```

### CODE REVIEW

**Comment by Eloston** [comment]
> Whatever it is that is happening here:

Maybe it's trying to run clang_format but it isn't able to find the executable?

**Comment by AKile9V** [comment]
> > Whatever it is that is happening here:
> 
> Maybe it's trying to run clang_format but it isn't able to find the executable?

Hi,
I think you are right, it's trying to run clang-format.exe on: ...\\src\\out\\Default\\gen\\third_party\\blink\\renderer\\bindings\\core\\v8\\v8_text_track_mode.h
but it isn't able to find it, because it doesn't exist in "out" directory.
How did you fix this issue on your macos build? Because I got the same error there...
I have tried to "delete" all dependencies "v8:generated" from various BUILD.gn files ( as well as generate_bindings_enumeration, generate_enumeration and every other associated stuffs ) and then it can build to the end with some more fixes ( like deleting more safe_browsing stuffs that cause build to fail ), but then after package.py, and installation, it doesn't even open chromium...
Probably this was a wrong way to fix that issue, but rn I'm learning how it works

**Comment by Luka-Filipovic** [comment]
Wouldn't it be smart to skip version 83 and focus on 84? There are some changes on v8 and maybe this problem can be bypassed.

**Comment by lipici** [comment]
good luck

**Pull request merged**
