### PR TITLE
Update to Chromium 90.0.4430.85

### PR DESCRIPTION
**Pull request by tangalbert919**
Notable changes:
  - Clang has been updated to 12.0.0 stable.

Current issues:
  - The build fails with this error: 
  ```../..\build/build_config.h(126) : error RC2188: ../..\build/build_config.h(201) : error RC2188: E:\ungoogled-chromium-windows\build\src\out\Default\obj\chrome\app\chrome_dll_resources\RCa11836(210) : fatal error RC1116: RC terminating after preprocessor errors```

### CODE REVIEW

**Comment by Dastardly-Entrench** [comment]
I hope it gets fixed soon.

**Comment by Nifury** [comment]
I was able to fix this build error:
https://gist.github.com/Nifury/2e48ef1299e49680c352e18c38dad628
but I still can't build Chromium without applying the safe-browsing patch. 
screenshot

**Comment by brodybits** [comment]
Is there anything we can do to help get ungoogled-chromium-windows updated to version 91 or 92?

**Comment by tangalbert919** [comment]
I'm closing this PR in favor of #93.

**Pull request closed without merging**
