### PR TITLE
Fix Python 3 detection

### PR DESCRIPTION
**Pull request by tangalbert919**
This should be very obvious.

### CODE REVIEW

**Comment by DaCoolX** [comment]
Didn't see this, this would fix #10 .

**Comment by Eloston** [comment]
I'm failing to understand why we need this PR. Would you mind elaborating?

For the same reason that we had Python 2.7 as `python` in `PATH`, we also need Python 3 as `python` in `PATH`. That is, the build expects Python to be available as `python`. I don't understand how using `py` will work here.

**Comment by tangalbert919** [comment]
We can't have Python 3 as `python` in `PATH` for a two reasons:

1. `build.py` still requires Python 2.7 to run GN bootstrap, as the bootstrap doesn't even run on Python 3. That means having Python 2.7 installed is still a requirement for building.
2. By default, Python 3 cannot be invoked with `python`, as that's already used to invoke Python 2. That's why we use `python3` or `py` instead.

If we were to leave `build.py` alone, we should expect anyone who builds to see an error like this:
image

**Comment by Eloston** [comment]
> By default, Python 3 cannot be invoked with python, as that's already used to invoke Python 2. That's why we use python3 or py instead.

Again, the goal is to use Python 3 for everything. We don't want Python 2.

> This error did not occur when Python 2 was set as python in PATH, so to be able to build, Python 2 has to be set as python in PATH, not Python 3.

Perhaps it hasn't been upgraded to Python 3 yet.

Also, are you saying that there are no `gn gen` errors with Python 2?

**Comment by tangalbert919** [comment]
> Again, the goal is to use Python 3 for everything. We don't want Python 2.
All of the scripts written by you (and possibly other developers for this project) are for Python 3, but Google's scripts (which have to be used for this to work) aren't.

> Also, are you saying that there are no `gn gen` errors with Python 2?
`gn gen` has been used with Python 2 for years, without any errors. It would not make sense for `gn gen` to have errors with Python 2 now.

**Comment by Eloston** [comment]
@tangalbert919 

> All of the scripts written by you (and possibly other developers for this project) are for Python 3, but Google's scripts (which have to be used for this to work) aren't.

I have been saying that Google **is** updating the scripts to Python 3. You can find the issue reports where they are tracking this progress in the Chromium bug tracker.

> gn gen has been used with Python 2 for years, without any errors. It would not make sense for gn gen to have errors with Python 2 now.

Well considering the Safe Browsing patch is a huge mess that touches quite a few GN files, I was just checking to see if this was the cause of the `gn gen` failure. `gn gen` can fail for many more reasons than an incorrect Python installation.

**Comment by Eloston** [comment]
I think https://github.com/ungoogled-software/ungoogled-chromium-windows/commit/29842a00a87b1445f7c7e5a09f6e728f8136933f should address this; I initially overlooked the s/stderr/stdout/ change. But my point about `py` vs `python` should still stand. Let me know if this is not the case.

**Pull request closed without merging**
