### PR TITLE
Update to ungoogled-chromium 105.0.5195.127-1

### PR DESCRIPTION
**Pull request by teeminus**
No patch updates required.

image

### CODE REVIEW

**Review by PF4Public — APPROVED** [review]

**Comment by teeminus** [comment]
@Nifury Publishing the release on winget has failed. Could you please have a look?

**Comment by networkException** [comment]
wym fail, its here: https://github.com/microsoft/winget-pkgs/pull/79942

**Comment by networkException** [comment]
oh that was a rerun, my bad

**Comment by Nifury** [comment]
Yeah turns out I need to keep my winget repo synced.

**Comment by PF4Public** [comment]
Is everything okay? Should I wait for @Nifury's approval first?

**Comment by Nifury** [comment]
@PF4Public Everything is fine. I'll submit a PR to sync the winget-pkgs repository automatically.

**Pull request merged**
