### PR TITLE
Update to ungoogled-chromium 108.0.5359.99-1

### PR DESCRIPTION
**Pull request by teeminus**
Builds and runs fine, no patch updates required.

image

### CODE REVIEW

**Review by PF4Public — APPROVED** [review]

**Comment by teeminus** [comment]
@Nifury Publishing on winget has failed, can you please have a look what went wrong?

**Comment by Nifury** [comment]
`` ! [remote rejected]       master -> master (refusing to allow a Personal Access Token to create or update workflow `.github/workflows/spellCheck.yaml` without `workflow` scope)``

I guess I'll have to create a new PAT with proper permissions. Could @networkException or @PF4Public make me admin for a moment so that I can update the secret?

**Comment by networkException** [comment]
Yep, given you admin

**Comment by Nifury** [comment]
@networkException Done 😀

**Pull request merged**
