### PR TITLE
Create winget.yml

### PR DESCRIPTION
**Pull request by Exorcism0666**
All you have to do is create a "WINGET_TOKEN" secret token with the necessary scopes, and bingo! you've just automated the output of your software for winget.

### CODE REVIEW

**Comment by PF4Public** [comment]
Is it not the case already?

**Comment by Exorcism0666** [comment]
Nope

**Comment by Exorcism0666** [comment]
Welp nevermind, I hadn't seen in the workflow that there was winget

**Comment by PF4Public** [comment]
AFAIK @Nifury made something for winget, am I wrong?

**Comment by Nifury** [comment]
Yeah I thought about using that Action for winget release, but we need to have 4 different scope/architecture combinations in one release which is not supported. 
https://github.com/microsoft/winget-pkgs/pull/133893

**Pull request closed without merging**
