### PR TITLE
Update to 103.0.5060.53-1

### PR DESCRIPTION
**Pull request by teeminus**
1. The `windows-fix-dawn-version-generator-git-path.patch` patch is no longer required (at least for me where GIT is in the PATH).
2. The `windows-fix-showIncludes.patch` is now applied to `build/toolchain/win/toolchain.gni` instead of `build/toolchain/win/BUILD.gn`. I also needed to fix an unused variable error as `toolchain_is_clang` seems to be not used in all cases.

### CODE REVIEW

**Review by Nifury — APPROVED** [review]
Builds and runs fine!

**Comment by teeminus** [comment]
I am waiting for at least one more review before I hit the merge button.

**Comment by PF4Public** [comment]
> I am waiting for at least one more review

It was intentional, that main repo needs two reviews and this one only one ;)

**Comment by teeminus** [comment]
Well, if it's like that then I will no longer delay the merge :-)

**Comment by teeminus** [comment]
Tag has been created, CI is running 😄

**Pull request merged**
