### PR TITLE
Automated release via Github Actions

### LINKED ISSUE #108: Cross building on Linux / GitHub Actions
It would be good to have automated releases using GitHub Actions. I've looked into the Windows runner a little and sadly due to how virtual drives are arranged I think its impossible to compile Chromium. The C: drive contains [preinstalled software](https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md) which is taking up a lot of space. On Linux it would be easy to [remove unused toolchains and similar](https://github.com/ungoogled-software/ungoogled-chromium-archlinux/blob/3d55adb7831a2a770821270faaa8818c92a58cce/.github/actions/stage/index.ts#L47) but the working directory for the Windows runner is located on D: which only has ~8GB of free storage.

As such I think to automate releases its nessesarry to [cross compile on Linux](https://chromium.googlesource.com/chromium/src/+/refs/heads/main/docs/win_cross.md). I [started working](https://github.com/networkException/ungoogled-chromium-windows/commit/600e7fad67e0f4b5c6783f84d3ca7b9e81af318b) on retrieving the Windows toolchain already but I'm not familiar with writing build scripts myself.

CC @wchen342 @Nifury could you help here maybe?

### PR DESCRIPTION
**Pull request by Nifury**
This PR adds CI to build and release ungoogled chromium for windows automatically. Thank @networkException for providing the multi-step building script. 

Fixes #108

### CODE REVIEW

**Comment by networkException** [comment]
Can you rebase this on top of the master branch?

**Review by networkException — APPROVED** [review]
LGTM

**Review by networkException — APPROVED** [review]
Great!

**Comment by Nifury** [comment]
I think it's because you set `is_official_build`. 
https://github.com/ungoogled-software/ungoogled-chromium/issues/1935#issuecomment-1122361329

**Comment by teeminus** [comment]
I intentionally did not set the flag in the last PR as the build process takes longer to finish and requires more HDD and RAM (at least on my machine). That's also mentioned in the issue referenced by @Nifury.

However, I'm curious to see how the compile time is affected in the CI. If it's not notably different, we could set the flag by default.

**Comment by LABPBS** [comment]
> It's because of the 'is_offical_build' flag. This requires an additional patch for the `generate_resource_allowlist.py` file to be applied which is normally not needed and therefore not included here.
> 
> In my fork of this repo, there is a branch with the flag set. You can find the required patch in this branch.

Thanks! giving it another shot at https://github.com/LABPBS/ungoogled-chromium-windows/actions/runs/2476986726


> However, I'm curious to see how the compile time is affected in the CI. If it's not notably different, we could set the flag by default.

24 hours in GHA for the failed one

**Comment by teeminus** [comment]
> > It's because of the 'is_offical_build' flag. This requires an additional patch for the `generate_resource_allowlist.py` file to be applied which is normally not needed and therefore not included here.
> 
> > 
> 
> > In my fork of this repo, there is a branch with the flag set. You can find the required patch in this branch.
> 
> 
> 
> Thanks! giving it another shot at https://github.com/LABPBS/ungoogled-chromium-windows/actions/runs/2476986726

Did the build succeed and if yes, how long did it take? The link you posted is no longer valid.

**Comment by playgithub** [comment]
Great!
Thanks

**Pull request merged**
