### PR TITLE
LICENSE: Update year and improve formatting

### PR DESCRIPTION
**Pull request by networkException**
This pull request also makes GitHub detect the license properly

### CODE REVIEW

**Comment by networkException** [comment]
This pr is so old the year is outdated again :sweat_smile:

**Comment by PF4Public** [comment]
> This pr is so old the year is outdated again 😅

And it will be so every year. Just drop it :)

**Comment by networkException** [comment]
I kind of like it as an indicator of the maintenance level..

**Comment by PF4Public** [comment]
> I kind of like it as an indicator of the maintenance level..

If you say so! I personally deeply hate repetitive work :)

**Pull request merged**
