### PR TITLE
Keep the forked winget-pkgs up to date

### PR DESCRIPTION
**Pull request by Nifury**
Fixes https://github.com/ungoogled-software/ungoogled-chromium-windows/actions/runs/3063256660/jobs/4961200855#step:4:145

### CODE REVIEW

**Comment by networkException** [comment]
A rebase pull might be better to avoid unnecessary merge commits

**Comment by Nifury** [comment]
How about a hard reset to upstream/master and force push? That makes sure we are always synced.

**Comment by networkException** [comment]
Yep that works too

**Comment by teeminus** [comment]
Are we ready to merge?

**Comment by Nifury** [comment]
We are 😀

**Comment by teeminus** [comment]
Looks good for me. @networkException?

**Review by teeminus — APPROVED** [review]

**Review by networkException — APPROVED** [review]
Yep (I have't seen this way of authenticating with github yet but I assume you know what you're doing :smile:)

**Comment by Nifury** [comment]
Oh you mean `x-access-token`? I copied it from [here](https://github.com/vedantmgoyal2009/winget-releaser/blob/f4c376e967bc9a0a9f6e9a9ccb76487b0f6e4ea0/index.js#L124) thought it was the standard way. 

Anyway it seems to work pretty well in my test.

**Pull request merged**
