### PR TITLE
Update to ungoogled-chromium 113.0.5672.127-1

### PR DESCRIPTION
**Pull request by teeminus**
Build and runs fine with https://github.com/ungoogled-software/ungoogled-chromium/pull/2352, https://github.com/ungoogled-software/ungoogled-chromium/pull/2337 lead to a minor change in one patch that's why I am recompiling to check if everything is still working.

Once compiling has finished, I will post an update.

### CODE REVIEW

**Comment by teeminus** [comment]
It seems like https://github.com/ungoogled-software/ungoogled-chromium/pull/2337 introduced some linking error for windows (below are some but probably not all):

```
LINK chromedriver.exe chromedriver.exe.pdb
FAILED: chromedriver.exe chromedriver.exe.pdb
..\..\third_party\llvm-build\Release+Asserts\bin\lld-link.exe /OUT:./chromedriver.exe /nologo -libpath:..\..\third_party\llvm-build\Release+Asserts\lib\clang\16\lib\windows "-libpath:../../../../../Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/ATLMFC/lib/x64" "-libpath:../../../../../Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/lib/x64" "-libpath:../../../../../Program Files (x86)/Windows Kits/NETFXSDK/4.8/lib/um/x64" "-libpath:../../../../../Program Files (x86)/Windows Kits/10/lib/10.0.22621.0/ucrt/x64" "-libpath:../../../../../Program Files (x86)/Windows Kits/10/lib/10.0.22621.0/um/x64" /MACHINE:X64  /PDB:./chromedriver.exe.pdb @./chromedriver.exe.rsp
lld-link: error: undefined symbol: struct std::Cr::pair<class GURL, enum net::ReferrerPolicy> __cdecl referrer_sanitizer::sanitize_referrer(class GURL const &, class GURL const &, enum net::ReferrerPolicy const &, bool)
>>> referenced by ../../services/network/network_service_network_delegate.cc
>>>               obj/services/network\network_service/network_service_network_delegate.obj
```

```
LINK v8_context_snapshot_generator.exe v8_context_snapshot_generator.exe.pdb
FAILED: v8_context_snapshot_generator.exe v8_context_snapshot_generator.exe.pdb
..\..\third_party\llvm-build\Release+Asserts\bin\lld-link.exe /OUT:./v8_context_snapshot_generator.exe /nologo -libpath:..\..\third_party\llvm-build\Release+Asserts\lib\clang\16\lib\windows "-libpath:../../../../../Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/ATLMFC/lib/x64" "-libpath:../../../../../Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/lib/x64" "-libpath:../../../../../Program Files (x86)/Windows Kits/NETFXSDK/4.8/lib/um/x64" "-libpath:../../../../../Program Files (x86)/Windows Kits/10/lib/10.0.22621.0/ucrt/x64" "-libpath:../../../../../Program Files (x86)/Windows Kits/10/lib/10.0.22621.0/um/x64" /MACHINE:X64  /PDB:./v8_context_snapshot_generator.exe.pdb @./v8_context_snapshot_generator.exe.rsp
lld-link: error: undefined symbol: struct std::Cr::pair<class GURL, enum network::mojom::ReferrerPolicy> __cdecl referrer_sanitizer::sanitize_referrer(class GURL const &, class GURL const &, enum network::mojom::ReferrerPolicy const &, bool)
>>> referenced by ../../third_party/blink/renderer/platform/loader/fetch/url_loader/dedicated_or_shared_worker_fetch_context_impl.cc
>>>               obj/third_party/blink/renderer/platform/loader/loader/dedicated_or_shared_worker_fetch_context_impl.obj
```

Unfortunatelly, I have no idea how to resolv those issues as I have no idea how the `gn` files work. I highly appreciate hints how to fix these problems. @Ahrotahn @networkException

**Comment by networkException** [comment]
it would be fine if you revert the patches for windows for now I'd say

**Comment by teeminus** [comment]
I tried the suggested patch but liking still failed at `v8_context_snapshot_generator.exe`.

I am not sure how to revert the referrer changes. Those changes are in the core repo and if I wanted to revert the changes, I would have to commit a dirty submodule. The referrer PR was merged before the .126/.127 PR and if I remember correctly, merging the referrer PR lead to changes in the .126/.127 PR. So I would have to revert two PRs and create an .127 update which differs slightly from the core repo. Or am I missing an easier way?

**Comment by teeminus** [comment]
> The namespacing wasn't needed after we changed the location, see if removing it helps:
Unfortunately, linking still failes with the changes applied.

> I think a temporary patch to remove that patch's line from the series file should work.
I think this could work, but I would need to temporarily change the windows toolchain for that. I try this next :)

**Comment by Ahrotahn** [comment]
Another idea would be to add the include to the builds for each reference:
<details><summary>diff</summary>

```diff
--- a/third_party/blink/renderer/platform/loader/BUILD.gn
+++ b/third_party/blink/renderer/platform/loader/BUILD.gn
@@ -178,6 +178,7 @@
   deps = [
     ":make_platform_loader_generated_delivery_type_names",
     ":make_platform_loader_generated_fetch_initiator_type_names",
+    "//chrome/common",
     "//components/link_header_util",
     "//components/variations/net:net",
     "//net",
--- a/services/network/BUILD.gn
+++ b/services/network/BUILD.gn
@@ -254,6 +254,7 @@
     "//base",
     "//build:chromecast_buildflags",
     "//build:chromeos_buildflags",
+    "//chrome/common",
     "//components/content_settings/core/common",
     "//components/cookie_config",
     "//components/domain_reliability",
```
</details>

**Comment by teeminus** [comment]
Compiling succedeed by removing the `add-flags-for-referrer-customization.patch` (for now). We could try including it in a `.2` release or wait for the next chromium update.

Thanks everybody for helping me solve the issue :)

image

**Comment by Rusenche** [comment]
Well done for the work and for solving the problem.

Realistically the next update will be on 30.05.2023 with the appearance of the stable version 114.

:}

**Pull request merged**
