### PR TITLE
Update to ungoogled-chromium 128.0.6613.113-1

### PR DESCRIPTION
**Pull request by teeminus**
Builds and runs fine, no patch updates required:

image

### CODE REVIEW

**Review by Nifury — APPROVED** [review]

**Comment by teeminus** [comment]
CI failed twice for both x86 and x64 when compiling gn:


```
[80/200] CXX src/gn/filesystem_utils.obj
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "C:\ungoogled-chromium-windows\build\src\tools\gn\bootstrap\bootstrap.py", line 142, in <module>
    sys.exit(main(sys.argv[1:]))
  File "C:\ungoogled-chromium-windows\build\src\tools\gn\bootstrap\bootstrap.py", line 128, in main
    subprocess.check_call(cmd)
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ninja', '-C', 'C:\\ungoogled-chromium-windows\\build\\src\\out\\Release\\gn_build', 'gn.exe']' returned non-zero exit status 1.
C:\ungoogled-chromium-windows\build\src>exit
Traceback (most recent call last):
  File "C:\ungoogled-chromium-windows\build.py", line 323, in <module>
    main()
  File "C:\ungoogled-chromium-windows\build.py", line 297, in main
    _run_build_process(
  File "C:\ungoogled-chromium-windows\build.py", line 67, in _run_build_process
    subprocess.run(('cmd.exe', '/k'),
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('cmd.exe', '/k')' returned non-zero exit status 1.
```

Were there any changes to the CI container? Something is wrong with the visual studio toolchain... @Nifury

**Comment by Nifury** [comment]
I think we need to set `_LEGACY_CODE_ASSUMES_STRING_VIEW_INCLUDES_XSTRING`.
I'll work on this. 
https://github.com/microsoft/STL/blob/91e425587a0b9b5ac0d1005844c661fee2e2813b/stl/inc/string_view#L14-L16

**Comment by Nifury** [comment]
This seems to have fixed the issue. 
https://github.com/Nifury/ungoogled-chromium-windows/commit/d0913316ffd7f31b87d5400a14a5d85473ed2301

**Comment by teeminus** [comment]
But why did it work before? Did they (GitHub) change anything? There were no GN changes between the last two releases.

**Comment by Nifury** [comment]
I think so. GitHub recently [updated](https://github.com/actions/runner-images/commit/891c2ed95c5061cea040db765f6d673e34b0787a#diff-d3119a278ce9ce80fc4b5af63a1112fb3a044aec3e6002d838e8eb26d7a3a499L223-R225) the Visual Studio version, 
which includes [a PR](https://github.com/microsoft/STL/pull/4633) that removes `<xstring>` from `<string_view>`, and has caused many compilation issues.

**Comment by teeminus** [comment]
Thanks a lot for digging into the problem. I included your fix in the next release: https://github.com/ungoogled-software/ungoogled-chromium-windows/pull/379

**Pull request merged**
