### PR TITLE
Update to ungoogled-chromium 107.0.5304.122-1

### PR DESCRIPTION
**Pull request by teeminus**
No patch updates required. It's still compiling, but if anyone is able to produce results faster we can merge before my build finishes.

### CODE REVIEW

**Review by PF4Public — APPROVED** [review]
Feel free to merge when your build finishes. Minor bumps are usually uneventful.

**Comment by PF4Public** [comment]
@teeminus when you have a working build, please check that `chrome://flags/#extension-mime-request-handling` wasn't lost. Just in case ;)

**Comment by Nifury** [comment]
@PF4Public 
Hibbiki is the vanilla Chromium build. Of course it has no such flag.

**Comment by PF4Public** [comment]
> Hibbiki is the vanilla Chromium build. Of course it has no such flag.

I was suspecting something like that :D

**Comment by teeminus** [comment]
It's compiling and working fine:
image

**Comment by teeminus** [comment]
> @teeminus when you have a working build, please check that `chrome://flags/#extension-mime-request-handling` wasn't lost. Just in case ;)

Still there :)
image

**Pull request merged**
