### PR TITLE
- Update to ungoogled-chromium 118.0.5993.70-2

### PR DESCRIPTION
**Pull request by Nifury**

### CODE REVIEW

**Comment by Rusenche** [comment]
> @PF4Public (5 hours ago): I do hope Windows users will appreciate that.

Of course.

It's a shame there isn't a working tool and/or alternative to Chrlauncher suitable for this repository, because @uazo provided such a facility to update when new versions of his Cromite are available.

**Comment by teeminus** [comment]
Binary releases for this repo are published in winget as well.

**Comment by uazo** [comment]
I take advantage of this, I apologise for the OT.
@PF4Public could i know if there is something wrong with chrlauncher that I don't know?

**Comment by PF4Public** [comment]
> if there is something wrong with chrlauncher that I don't know

It has a setting to allegedly download ungoogled-chromium. As a matter of fact it does _not_ download ungoogled-chromium from this organisation. Instead it uses some third-party binaries unrelated to ungoogled-chromium and not published within ungoogled-chromium organisation. Those binaries sometimes include your patches with JIT disabled by default for example, which we do not do here. Users falsely believing they are using ungoogled-chromium file issues here. And this _is_ a problem. I suggested the author of chrlauncher to either clearly state that selecting ungoogled-chromium users do not download ungoogled-chromium, or to change this option not to mention ungoogled-chromium. Both suggestioons were rejected without expressing any reasoning for that.

**Comment by uazo** [comment]
Ok, thanks (even if it is not ok), I was thinking of some issue in the application itself.

 > Those binaries sometimes include your patches with JIT disabled by default for example, which we do not do here

I know this, I am sorry that they use your name to create something that has no public source code.
But the only solution I see is to brand your executable.

**Comment by PF4Public** [comment]
> I was thinking of some issue in the application itself

Haven't tried myself, so cannot asses.

> But the only solution I see is to brand your executable

True, but we're not lawyers and such legal processes are outside of our scope of interests. We maintain ungoogled-chromium, which is more important and valuable.

**Comment by Rusenche** [comment]
In practice, the `Chrlauncher` app does not work for this repository, and we cannot update when there are new versions of Ungoogled chromium, because the author (@henrypp) flatly refuses to write why he does not want to add an address to this repository.

https://github.com/henrypp/chrlauncher/issues/217- the thread is from 14 and a half months ago.

But @uazo has elegantly solved this problem for his Cromite.

**Comment by uazo** [comment]
everything suggests that it is better to stay away from those executables...
years ago when I tried ungoogled I too think I used those and that I stopped using ungoogled because I was catching a series of viruses inexplicably...

**Comment by networkException** [comment]
"chrlauncher considered harmful"

**Pull request merged**
