### PR TITLE
102.0.5005.61-3

### PR DESCRIPTION
**Pull request by teeminus**
I completely reworked the windows-fix-building-without-safebrowsing patch. I tried compiling without the patch and fixed all compile errors until compiling finally succeeded. All fixes are now in the new windows-fix-building-without-safebrowsing patch file. The last thing to fix was the missing safe_browsing.lib. It turned out that any lib file will work here so I created an empty source file (safe_browsing_dummy.cc) which leads to an empty safe_browsing.lib beeing created.

### CODE REVIEW

**Comment by teeminus** [comment]
Updated to 99.0.4844.82-1

**Comment by Nifury** [comment]
It builds and runs fine, thank you!
With the safe browsing patch reworked, updating to future versions should be much easier. Good job!

**Comment by ekumlin** [comment]
Is this version still in the works, or is it possible to have it merged? (Ideally along with #125)

**Comment by teeminus** [comment]
Updated to 99.0.4844.84-1

**Comment by teeminus** [comment]
Itried to update to the latest 100.0.4896.60-1.but got the following error message while compiling:
```
C:\ucw\build\src>"third_party\ninja\ninja.exe" "-C" "out\Default" "chrome" "chromedriver" "mini_installer"
ninja: Entering directory `out\Default'
ninja: error: '../../third_party/devtools-frontend/src/third_party/esbuild/esbuild.exe', needed by 'gen/third_party/devtools-frontend/src/inspector_overlay/common.js', missing and no known rule to make it
```

Does anybody know how to fix this issue?

**Comment by PF4Public** [comment]
try `"third_party\ninja\ninja.exe" "-C" "out\Default" "chrome"`

**Comment by Nifury** [comment]
I don't know why it's not an issue in the previous versions, but putting `esbuild.exe` into that directory seems to solve this error. 
https://esbuild.github.io/getting-started/#download-a-build

**Comment by teeminus** [comment]
> try `"third_party\ninja\ninja.exe" "-C" "out\Default" "chrome"`

This did not not work.

> I don't know why it's not an issue in the previous versions, but putting `esbuild.exe` into that directory seems to solve this error. https://registry.npmjs.org/esbuild-windows-64/-/esbuild-windows-64-0.14.13.tgz

I asked myself the same. Either esbuild was not needed before or it somehow got downloaded before the actual build started. I will try the changes proposed by https://github.com/ungoogled-software/ungoogled-chromium-windows/pull/142 and hope this will fix the problem.

**Comment by teeminus** [comment]
The esbuild download fix from #142 worked and chromium 100 compiled successfully.

**Comment by srappan** [comment]
Is there a maintainer, that can merge these requests. The current repo is very outdated.  The update is priority for the binaries too, (bunch 0 days were patched) if we get GitHub actions working we can automate binaries too.

**Comment by srappan** [comment]
Apologies for the ping @Eloston, could we merge these PRs asap? #142 #139

**Comment by tangalbert919** [comment]
I think a few people here already saw my alternate solution in #142, but for those who didn't, here's what I proposed:

```diff
--- a/downloads.ini
+++ b/downloads.ini
@@ -93,3 +93,11 @@ sha256 = b93b73572c5e495154a9823d494de5729c77d1c83b041171154c4b5f3f76b590
 extractor = 7z
 output_path = third_party/node/win
 strip_leading_dirs=node-v%(version)s-win-x64
+
+# esbuild
+[esbuild]
+version = 0.14.13
+url = https://registry.npmjs.org/esbuild-windows-64/-/esbuild-windows-64-%(version)s.tgz
+download_filename = esbuild-windows-64-%(version)s.tgz
+output_path = third_party/devtools-frontend/src/third_party/esbuild
+strip_leading_dirs=package
-- 
```

**Comment by teeminus** [comment]
Done, PR now is for 100.0.4896.60-1.

**Comment by teeminus** [comment]
Updated to 100.0.4896.75-1

**Comment by networkException** [comment]
Thank you for your continued effort, I hope that we will be able to merge this soon. Sadly I don't think any active user has permission to push to this repository at the moment.

I'm awaiting feedback from Eloston on an internal discussion that would hopefully allow us to update the Windows packaging way more closely to the patchset release cycle

**Comment by teeminus** [comment]
Updated to 100.0.4896.88-1

**Comment by teeminus** [comment]
Update to 100.0.4896.127-1

**Comment by PF4Public** [comment]
> I'm awaiting feedback from Eloston on an internal discussion that would hopefully allow us to update the Windows packaging way more closely to the patchset release cycle

Uh Oh! I didn't realize, we do not have access to windows repo! I'll ping @Eloston about that.

**Comment by networkException** [comment]
Yea that's https://github.com/orgs/ungoogled-software/teams/core/discussions/7 basically. I also wrote him an email about it (although I seem to have linked the wrong discussion, woops)

Anyways its totally fine to cut on voluntary work first when life gets busy so don't worry about taking your time Eloston

**Comment by teeminus** [comment]
Update to 101.0.4951.41-1

I had to update LLVM to the latest version as some c++20 features were not support in the previous version.

**Comment by teeminus** [comment]
Update to 101.0.4951.54-1

**Comment by PF4Public** [comment]
@teeminus Did you manually edit the patch to overcome Eloston/ungoogled-chromium#1935?

**Comment by teeminus** [comment]
No, I updated the safebrowsing patch so that compiling succeeds automatically.

But I am not quite sure if the fix I added to the patch is the best solution for the problem. That's why I created the issue in the other repo because I thought this can't we a windows only problem. And I think the fewer patches we have to apply here the better...

**Comment by PF4Public** [comment]
> this can't be a windows only problem

Well, it does work on Linux without issues, idk…

**Comment by teeminus** [comment]
That's what made me wonder...

**Comment by teeminus** [comment]
In the end it's a linking error. In the windows safebrowsing patch there are a few more fixes for linking errors that seem to only occur on windows.

Either the general build process for windows is slightly different or the linker is not as "smart" as for eg. linux.

**Comment by teeminus** [comment]
By the way, is using the build flag `is_official_build` recommended? If yes, I would like to add it to this PR as is reduces the installer/package size.

**Comment by teeminus** [comment]
Update to 101.0.4951.64-1

**Comment by teeminus** [comment]
> > By the way, is using the build flag `is_official_build` recommended? If yes, I would like to add it to this PR as is reduces the installer/package size.
> 
> [Eloston/ungoogled-chromium#1935 (comment)](https://github.com/Eloston/ungoogled-chromium/issues/1935#issuecomment-1121444527)

Ah sorry, that comment completely slipped through. When the `is_offical_build` flag is set, linking takes significantly longer, on my setup I would guess at least one hour. And it takes a lot more resources:
image

I am not sure if the linker takes that amount of memory because it needs that much or just because it can... And I am also not sure if all systems that are currently able to build this project will be able to do so once the flag is enabled. Which includes the github CI...

I created a new branch which has the `is_offical_build` flag set for anyone willing to try it out: https://github.com/teeminus/ungoogled-chromium-windows/tree/enable_is_official_build

**Comment by teeminus** [comment]
> If possible, can you incorporate [this patch](https://github.com/Nifury/ungoogled-chromium-windows/blob/44a22488a6ad93736ece362343313462a7af6917/patches/ungoogled-chromium/windows/windows-fix-rc-terminating-error.patch) as well so that I can build chromium x86 via CI as well?
> 
> 
> 
> Thanks!
> 
> 
> 
> ref: #124 

@Nifury You just need the `RC_INVOKED` definition check in the `build/build_config.h`?

**Comment by teeminus** [comment]
> > @Nifury You just need the `RC_INVOKED` definition check in the `build/build_config.h`?
> 
> 
> 
> Yes, so that MSVC RC compiler does not parse and compile this file (otherwise causes RC1116). 

Done

**Comment by teeminus** [comment]
I have no idea why the file `chrome/app/chrome_command_ids.h` needs to be patched at all. Those ifdefs should (normally) work...

**Comment by teeminus** [comment]
But shouldn't other files be affected as well then?

On my system no error is thrown at the `IS_LINUX` ifdef.

**Comment by Nifury** [comment]
Very few header files are included in `.rc` files. Unfortunately `chrome_command_ids.h` is one of them.

**Comment by teeminus** [comment]
I updated the patch and added a note why the changes are required.

**Comment by teeminus** [comment]
Update to 102.0.5005.61-1.

The Windows 10 SDK version required to build chromium has been changed to 10.0.20348.0. (see [here](https://chromium.googlesource.com/chromium/src/+/refs/heads/main/docs/windows_build_instructions.md#visual-studio))

**Review by Nifury — APPROVED** [review]
Builds and runs fine!

**Comment by PF4Public** [comment]
Go ahead :)

**Comment by teeminus** [comment]
Can I create a tag from the github site without creating a release?

**Comment by teeminus** [comment]
Okay, done :)

**Pull request merged**
