### PR TITLE
Use new cloning script

### PR DESCRIPTION
**Pull request by teeminus**
With this PR, the new cloning script is used for acquiring the chromium sources. However, the "old" tarball method can still be used by passing `--tarball` to the `build.py` script.

Implementing the new feature was quite simple. When using the clone script, we only need the windows `downloads.ini`. Instead of downloading and unpacking the tarball, we just call the clone script (which now uses PGO for windows). As the sources differ slightly compared to the tarball, we need to use a windows specific `pruning.list`. While generating the `pruning.list`, a new `domain_substitution.list` is generated as well. This file does currently not differ from file checked into the `ungoogled-chromium` repo, but in case this changes in the future we are using the file from the windows repo now.

I also updated the README for the new update process.

### CODE REVIEW

**Comment by Nifury** [comment]
I assume the CI script needs to be updated as well? It still uses cmd instead of the developer prompt for VS.

**Comment by teeminus** [comment]
I always thought one should use the developer command prompt for compiling and thought I should fix the bug in the readme while updating it. I just ran a short test in a normal cmd shell and so far it just works fine (at least it starts the cloning process).

Shall I revert the cmd change and change the other readme parts as well?

**Comment by Nifury** [comment]
https://github.com/Nifury/ungoogled-chromium-windows/actions/runs/6852770418/job/18632070726#step:5:916
Seems that it is not out-of-the-box compatible with the CI script. I'll look into this.

**Comment by teeminus** [comment]
Maybe python version used in the CI is to old? https://github.com/Nifury/ungoogled-chromium-windows/actions/runs/6852770418/job/18632070726#step:5:920

**Comment by Nifury** [comment]
Yeah depot_tools requires Python 3.8

**Comment by Nifury** [comment]
Noooo how did I push to your repo...

**Comment by PF4Public** [comment]
> Noooo how did I push to your repo...

image

**Review by Nifury — APPROVED** [review]

**Comment by teeminus** [comment]
I'll wait for your pipeline to finish before merging.

**Comment by Nifury** [comment]
No idea why the pipeline failed but I guess it's safe to merge.

**Comment by teeminus** [comment]
Looks like some kind of artifacts problem. But x86 finished compiling. If @PF4Public or @networkException  are okay with that I'll merge.

**Comment by PF4Public** [comment]
If that's a random fluke, we can merge of course.

**Review by PF4Public — APPROVED** [review]

**Pull request merged**
