### PR TITLE
- Update to ungoogled-chromium 105.0.5195.54-1

### PR DESCRIPTION
**Pull request by teeminus**
Some minor updates for the patches were required and I had to add a new patch to fix an import error in `tools/polymer/html_minifier.js`

Builds and runs fine:
image

### CODE REVIEW

**Comment by Nifury** [comment]
Instead of patching `html_minifier.js`, maybe it's better to update node? Node 12 seems way too outdated.

**Comment by Nifury** [comment]
It compiles and runs with node 16.

**Review by Nifury — APPROVED** [review]

**Comment by teeminus** [comment]
I updated nodejs to the latests LTS release. @Nifury csn you please check if the changes are correct? I did not recompile.

**Comment by R-T-B** [comment]
> I updated nodejs to the latests LTS release. @Nifury csn you please check if the changes are correct? I did not recompile.

16.7.0?  I may not be a regular contributor but isn't latest LTS 16.17.0?

**Comment by teeminus** [comment]
Yes, good catch. I fixed that.

**Comment by Nifury** [comment]
Looks good to me, but we can wait for @R-T-B to confirm.

**Comment by R-T-B** [comment]
Compiled fine with suggested changes.

**Review by Nifury — APPROVED** [review]

**Pull request merged**
