### PR TITLE
Update to ungoogled-chromium 106.0.5249.103-1

### PR DESCRIPTION
**Pull request by teeminus**
Builds and runs fine, no patch updates required.

image

### CODE REVIEW

**Review by Nifury — APPROVED** [review]

**Comment by teeminus** [comment]
@Nifury I think we need another build-step in the CI. For the current pipeline, x64 did not compile before stage-6 timeouted...

Can we somehow fix the the current release or do we need a dedicated release for that?

**Comment by Nifury** [comment]
Ah I'll fix this soon. Theoretically we can delete the current tag and add it to the new commit, but adding `-2` might be a better idea.

**Comment by Nifury** [comment]
Bummer. I forgot to update these lines. 
https://github.com/ungoogled-software/ungoogled-chromium-windows/blob/ec7903d1c24bfdc34bec824d9bdf7f9a6e749e50/.github/workflows/main.yml#L356

**Comment by teeminus** [comment]
I have no idea how to do that... @networkException ?

**Comment by Nifury** [comment]
I just created a draft. We can publish it if it looks good to you.

**Comment by teeminus** [comment]
Seems to be okay. Would you please create a new PR that fixes the CI? We can test the CI with the upcomming 106.0.5249.119 release.

**Pull request merged**
