### PR TITLE
Download esbuild in build.py

### PR DESCRIPTION
**Pull request by Nifury**
Chromium v100 adds esbuild as its dependency, but esbuild.exe is not shipped with the source. 

This PR updates build.py to download esbuild from CIPD packages (some code is borrowed from LUCI Python Client).

I know it's risky to call `exec()`, but I couldn't find a better way to parse the `DEPS` file without introducing external dependencies.

### CODE REVIEW

**Comment by teeminus** [comment]
Works like a charm, thank you ver much 👍

**Comment by tangalbert919** [comment]
You could also just append something like this to `downloads.ini`:

```
# esbuild
[esbuild]
version = 0.14.31
url = https://registry.npmjs.org/esbuild-windows-64/-/esbuild-windows-64-%(version)s.tgz
download_filename = esbuild-windows-64-%(version)s.tgz
sha256 = 601103c4ce6518226887d50f517e8d6f683bdb15256dec6658278094f21b584d
extractor = 7z
output_path = third_party/devtools-frontend/src/third_party/esbuild
strip_leading_dirs=package
```

The idea is to avoid downloading Google binaries and still fulfill required dependencies.

**Comment by Nifury** [comment]
@tangalbert919 True, but version `0.14.31` doesn't work. It has to match the version defined in `DEPS`. That's why I inclined to leave `downloads.ini` as it is.

**Comment by tangalbert919** [comment]
If you need an older version, that can be downloaded with the same URL by just modifying `version` and `sha256`, although just because the versions differ does not always mean it will not work.

Just as an example, we are still using Node.js `12.16.1`, even though the version defined in `DEPS` for that is `16.13.0`. It's not being downloaded from CIPD, and we have not run into problems with this so far, although we should update what version of Node.js we download soon.

**Comment by Nifury** [comment]
I tried to compile with the latest esbuild, and got an error saying version mismatch. 
My hypothesis is that, unlike Node.js, the esbuild version has to strictly match the one defined in `DEPS`. 
Though I'm not sure if an older version works.

**Comment by tangalbert919** [comment]
I don't think we need to worry about updating `downloads.ini` very often because esbuild 0.14.13 was added through [CR#3419383](https://chromium-review.googlesource.com/c/devtools/devtools-frontend/+/3419383) back in January, and it hasn't been updated since. Chromium 102 is still using esbuild 0.14.13 (even though it is in dev branch), so chances are we won't have to worry about that for the next few months.

If we need to use esbuild 0.14.13, then we should go for that. I'm just concerned with downloading it from any place but Google's servers.

**Comment by Nifury** [comment]
You've made your point. I'll close this PR. 
Maybe @teeminus can update `downloads.ini` in his PR?

**Comment by teeminus** [comment]
Sure, I will update my branch with the proposed changes and check if everything works as expected. I won't completely recompile though 😂

**Comment by teeminus** [comment]
Done, compiling of chrome starts without breaking because of the missing esbuild binary.

**Pull request closed without merging**
